#!/bin/sh

setup_ssh() {
  if dir_exists "${HOME}/.ssh"; then
    echo "SSH config directory exists, assuming all is setup"
  else
    echo "Generating security key for this system"
    ssh-keygen -b 4096
    echo ""
    echo "Please import the following public keypair into Github and Gitlab"
    echo "before continuing!"
    echo ""
    cat "${HOME}/.ssh/id_rsa.pub"
    echo ""
    echo "Press enter to continue"
    read -r nothing
    echo "${nothing}"
  fi
}
